version: "3.3"

services:
  web-prod:
    image: "jamerst/jobhunt:latest"
    ports:
      - "80:5000"
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - jobhunt-data:/jobhunt-data
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Screenshots__Schedule: "*/15 * * * *"
      Screenshots__Directory: "/jobhunt-data/page-screenshots"
      Screenshots__WidthPixels: 1920
      Screenshots__QualityPercent: 80
      Screenshots__PageLoadTimeoutSeconds: 10
      Search__IndeedPublisherId: YOUR_PUBLISHER_ID
      Search__IndeedFetchSalary: "true"
      Search__GlassdoorPartnerId: YOUR_PARTNER_ID
      Search__GlassdoorPartnerKey: YOUR_PARTNER_KEY
      Search__Schedules__0: 0 9 * * *
      Search__Schedules__1: 0 12 * * *
      Search__Schedules__2: 0 18 * * *
      Search__NominatimCountryCodes: "gb"
      Search__PageLoadWaitSeconds: 5
      Serilog__WriteTo__0__Name: "Console"
      # Serilog__WriteTo__0__Name: "Elasticsearch"
      # Serilog__WriteTo__0__Args__nodeUris: "http://elasticsearch:9200"
      # Serilog__WriteTo__0__Args__indexFormat: "jobhunt-serilog-{0:yyyy.MM}"
      TZ: "Europe/London"
      CultureName: "en-GB"
    networks:
      - jobhunt
      - docker_logging
    restart: always
    shm_size: '1gb'
  db:
    image: "postgres:13.2"
    environment:
        POSTGRES_DB: jobhunt_db
        POSTGRES_USER: jobhunt
        POSTGRES_PASSWORD: jobhunt
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-data/initdb.d:/docker-entrypoint-initdb.d/
    networks:
      - jobhunt
    restart: always

volumes:
  postgres-data:
  jobhunt-data:

networks:
  jobhunt:
    driver: bridge
  docker_logging:
    external: true