version: "3.3"

services:
  web-prod:
    image: "jamerst/jobhunt:latest"
    ports:
      - "80:5000"
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Search__IndeedPublisherId: YOUR_PUBLISHER_ID
      Search__IndeedFetchSalary: "true"
      Search__GlassdoorPartnerId: YOUR_PARTNER_ID
      Search__GlassdoorPartnerKey: YOUR_PARTNER_KEY
      Search__Schedules__0: 0 9 * * *
      Search__Schedules__1: 0 12 * * *
      Search__Schedules__2: 0 18 * * *
      Search__NominatimCountryCodes: "gb"
    restart: always
  db:
    image: "postgres:13.2"
    environment:
        POSTGRES_DB: jobhunt_db
        POSTGRES_USER: jobhunt
        POSTGRES_PASSWORD: jobhunt
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-data/initdb.d:/docker-entrypoint-initdb.d/
    restart: always
volumes:
  postgres-data: