FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Add repo for node
RUN apt-get update
RUN apt-get install -y ca-certificates curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_22.x |  bash -

# install node and npm
RUN apt-get update
RUN apt-get install -y --no-install-recommends nodejs unzip libfreetype6 libfontconfig1 ca-certificates procps pandoc firefox-esr jq

# install pnpm
RUN npm install -g pnpm

# install Visual Studio debugger
RUN curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /vsdbg

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# download and install geckodriver
COPY install-geckodriver.sh ./
RUN ./install-geckodriver.sh

ENTRYPOINT dotnet watch run --urls=https://+:5000