version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ./:/app:Z
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro,Z
      - /etc/localtime:/etc/localtime:ro
      - jobhunt-data:/jobhunt-data
    environment:
      # PageWatcher__ScreenshotSchedule: "* * * * *"
      Screenshots_Directory: "/jobhunt-data/page-screenshots"
      Screenshots_QualityPercent: 80
      Screenshots_WidthPixels: 1920
      Screenshots_PageLoadTimeoutSeconds: 10
      Search__IndeedFetchSalary: "true"
      # Search__Schedules__0: "* * * * *"
      Search__NominatimCountryCodes: "gb"
      Serilog__WriteTo__0__Name: "Console"
      # Serilog__WriteTo__0__Name: "Elasticsearch"
      # Serilog__WriteTo__0__Args__nodeUris: "http://elasticsearch:9200"
      # Serilog__WriteTo__0__Args__indexFormat: "jobhunt-serilog-{0:yyyy.MM}"
      WDS_SOCKET_PORT: "5000"
      TZ: "Europe/London"
    networks:
      - jobhunt
      - docker_logging
  db:
    image: "postgres:13.1"
    environment:
        POSTGRES_DB: jobhunt_db
        POSTGRES_USER: jobhunt
        POSTGRES_PASSWORD: jobhunt
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-data/initdb.d:/docker-entrypoint-initdb.d/
    networks:
      - jobhunt

volumes:
  postgres-data:
  jobhunt-data:

networks:
  jobhunt:
    driver: bridge
  docker_logging:
    external: true