CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Alerts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Read" boolean NOT NULL,
    "Type" text NOT NULL,
    "Title" text NOT NULL,
    "Message" text NULL,
    "Url" text NULL,
    "Created" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Alerts" PRIMARY KEY ("Id")
);

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Companies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Location" text NOT NULL,
    "Latitude" double precision NULL,
    "Longitude" double precision NULL,
    "Notes" text NULL,
    "Watched" boolean NOT NULL,
    "Blacklisted" boolean NOT NULL,
    "Website" text NULL,
    "Rating" smallint NULL,
    "Glassdoor" text NULL,
    "GlassdoorId" text NULL,
    "GlassdoorRating" real NULL,
    "LinkedIn" text NULL,
    "Endole" text NULL,
    CONSTRAINT "PK_Companies" PRIMARY KEY ("Id")
);

CREATE TABLE "Searches" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Provider" text NOT NULL,
    "Query" text NOT NULL,
    "Country" text NOT NULL,
    "Location" text NULL,
    "Distance" integer NULL,
    "MaxAge" integer NULL,
    "LastResultCount" integer NULL,
    "LastFetchSuccess" boolean NULL,
    "Enabled" boolean NOT NULL,
    "EmployerOnly" boolean NOT NULL,
    "JobType" text NULL,
    "LastRun" timestamp without time zone NULL,
    CONSTRAINT "PK_Searches" PRIMARY KEY ("Id")
);

CREATE TABLE "CompanyCategories" (
    "CompanyId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "PK_CompanyCategories" PRIMARY KEY ("CompanyId", "CategoryId"),
    CONSTRAINT "FK_CompanyCategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CompanyCategories_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CompanyNames" (
    "CompanyId" integer NOT NULL,
    "Name" text NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT "PK_CompanyNames" PRIMARY KEY ("CompanyId", "Name"),
    CONSTRAINT "FK_CompanyNames_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WatchedPages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "Url" text NOT NULL,
    "Hash" text NULL,
    "CssSelector" text NULL,
    "CssBlacklist" text NULL,
    "LastScraped" timestamp without time zone NULL,
    "LastUpdated" timestamp without time zone NULL,
    "StatusMessage" text NULL,
    "Enabled" boolean NOT NULL,
    CONSTRAINT "PK_WatchedPages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WatchedPages_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Jobs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Salary" text NULL,
    "AvgYearlySalary" integer NULL,
    "Location" text NOT NULL,
    "Latitude" double precision NULL,
    "Longitude" double precision NULL,
    "Url" text NULL,
    "CompanyId" integer NULL,
    "Posted" timestamp without time zone NULL,
    "Notes" text NULL,
    "Seen" boolean NOT NULL,
    "Archived" boolean NOT NULL,
    "Status" text NOT NULL,
    "DateApplied" timestamp without time zone NULL,
    "Provider" text NULL,
    "ProviderId" text NULL,
    "SourceId" integer NULL,
    CONSTRAINT "PK_Jobs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Jobs_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Jobs_Searches_SourceId" FOREIGN KEY ("SourceId") REFERENCES "Searches" ("Id") ON DELETE SET NULL
);

CREATE TABLE "SearchRuns" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SearchId" integer NOT NULL,
    "Time" timestamp without time zone NOT NULL,
    "Success" boolean NOT NULL,
    "Message" text NULL,
    "NewJobs" integer NOT NULL,
    "NewCompanies" integer NOT NULL,
    "TimeTaken" integer NOT NULL,
    CONSTRAINT "PK_SearchRuns" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SearchRuns_Searches_SearchId" FOREIGN KEY ("SearchId") REFERENCES "Searches" ("Id") ON DELETE CASCADE
);

CREATE TABLE "JobCategories" (
    "JobId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "PK_JobCategories" PRIMARY KEY ("JobId", "CategoryId"),
    CONSTRAINT "FK_JobCategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_JobCategories_Jobs_JobId" FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CompanyCategories_CategoryId" ON "CompanyCategories" ("CategoryId");

CREATE INDEX "IX_JobCategories_CategoryId" ON "JobCategories" ("CategoryId");

CREATE INDEX "IX_Jobs_CompanyId" ON "Jobs" ("CompanyId");

CREATE INDEX "IX_Jobs_SourceId" ON "Jobs" ("SourceId");

CREATE INDEX "IX_SearchRuns_SearchId" ON "SearchRuns" ("SearchId");

CREATE INDEX "IX_WatchedPages_CompanyId" ON "WatchedPages" ("CompanyId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210606154030_InitialCreate', '6.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE "Companies" ADD "Recruiter" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210926181747_CompanyRecruiter', '6.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE "WatchedPages" ALTER COLUMN "LastUpdated" TYPE timestamp with time zone;

ALTER TABLE "WatchedPages" ALTER COLUMN "LastScraped" TYPE timestamp with time zone;

ALTER TABLE "SearchRuns" ALTER COLUMN "Time" TYPE timestamp with time zone;

ALTER TABLE "Searches" ALTER COLUMN "LastRun" TYPE timestamp with time zone;

ALTER TABLE "Jobs" ALTER COLUMN "Posted" TYPE timestamp with time zone;

ALTER TABLE "Jobs" ALTER COLUMN "DateApplied" TYPE timestamp with time zone;

ALTER TABLE "Alerts" ALTER COLUMN "Created" TYPE timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211109213143_NpgSql6.0_DateTimeUtc', '6.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE "WatchedPages" DROP COLUMN "Hash";

CREATE TABLE "WatchedPageChanges" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WatchedPageId" integer NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "Html" text NOT NULL,
    CONSTRAINT "PK_WatchedPageChanges" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WatchedPageChanges_WatchedPages_WatchedPageId" FOREIGN KEY ("WatchedPageId") REFERENCES "WatchedPages" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_WatchedPageChanges_WatchedPageId" ON "WatchedPageChanges" ("WatchedPageId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220130142134_WatchedPageChange', '6.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE "WatchedPageChanges" ADD "ScreenshotFileName" text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220324201057_WatchedPageChange_Screenshot', '6.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE "WatchedPages" ADD "RequiresJS" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220404191815_WatchedPage_RequiresJS', '6.0.6');

COMMIT;

START TRANSACTION;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

ALTER TABLE "Jobs" ADD "DuplicateJobId" integer NULL;

CREATE INDEX "IX_Jobs_Description" ON "Jobs" USING gin ("Description" gin_trgm_ops);

CREATE INDEX "IX_Jobs_DuplicateJobId" ON "Jobs" ("DuplicateJobId");

CREATE INDEX "IX_Jobs_Title" ON "Jobs" USING gin ("Title" gin_trgm_ops);

ALTER TABLE "Jobs" ADD CONSTRAINT "FK_Jobs_Jobs_DuplicateJobId" FOREIGN KEY ("DuplicateJobId") REFERENCES "Jobs" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220626153835_DuplicateJobs', '6.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE "Jobs" ADD "ActualCompanyId" integer NULL;

ALTER TABLE "Jobs" ADD "Deleted" boolean NOT NULL DEFAULT FALSE;

CREATE INDEX "IX_Jobs_ActualCompanyId" ON "Jobs" ("ActualCompanyId");

ALTER TABLE "Jobs" ADD CONSTRAINT "FK_Jobs_Companies_ActualCompanyId" FOREIGN KEY ("ActualCompanyId") REFERENCES "Companies" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220717140709_Job_ActualCompany_Deleted', '6.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE "Jobs" ALTER COLUMN "Posted" SET NOT NULL;
ALTER TABLE "Jobs" ALTER COLUMN "Posted" SET DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Jobs" ALTER COLUMN "CompanyId" SET NOT NULL;
ALTER TABLE "Jobs" ALTER COLUMN "CompanyId" SET DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220813150214_Company_Posted_Required', '6.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE "Jobs" ADD "CheckedForDuplicate" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220814175931_Job_CheckedForDuplicate', '6.0.6');

COMMIT;