CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Alerts" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Read" boolean NOT NULL,
    "Type" text NOT NULL,
    "Title" text NOT NULL,
    "Message" text NULL,
    "Url" text NULL,
    "Created" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Alerts" PRIMARY KEY ("Id")
);

CREATE TABLE "Categories" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Companies" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Location" text NOT NULL,
    "Latitude" double precision NULL,
    "Longitude" double precision NULL,
    "Notes" text NULL,
    "Watched" boolean NOT NULL,
    "Blacklisted" boolean NOT NULL,
    "Website" text NULL,
    "Rating" smallint NULL,
    "Glassdoor" text NULL,
    "GlassdoorId" text NULL,
    "GlassdoorRating" real NULL,
    "LinkedIn" text NULL,
    "Endole" text NULL,
    CONSTRAINT "PK_Companies" PRIMARY KEY ("Id")
);

CREATE TABLE "Searches" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Provider" text NOT NULL,
    "Query" text NOT NULL,
    "Country" text NOT NULL,
    "Location" text NULL,
    "Distance" integer NULL,
    "MaxAge" integer NULL,
    "LastResultCount" integer NULL,
    "LastFetchSuccess" boolean NULL,
    "Enabled" boolean NOT NULL,
    "EmployerOnly" boolean NOT NULL,
    "JobType" text NULL,
    "LastRun" timestamp without time zone NULL,
    CONSTRAINT "PK_Searches" PRIMARY KEY ("Id")
);

CREATE TABLE "CompanyCategories" (
    "CompanyId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "PK_CompanyCategories" PRIMARY KEY ("CompanyId", "CategoryId"),
    CONSTRAINT "FK_CompanyCategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CompanyCategories_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CompanyNames" (
    "CompanyId" integer NOT NULL,
    "Name" text NOT NULL,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT "PK_CompanyNames" PRIMARY KEY ("CompanyId", "Name"),
    CONSTRAINT "FK_CompanyNames_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WatchedPages" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "Url" text NOT NULL,
    "Hash" text NULL,
    "CssSelector" text NULL,
    "CssBlacklist" text NULL,
    "LastScraped" timestamp without time zone NULL,
    "LastUpdated" timestamp without time zone NULL,
    "StatusMessage" text NULL,
    "Enabled" boolean NOT NULL,
    CONSTRAINT "PK_WatchedPages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WatchedPages_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Jobs" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Salary" text NULL,
    "AvgYearlySalary" integer NULL,
    "Location" text NOT NULL,
    "Latitude" double precision NULL,
    "Longitude" double precision NULL,
    "Url" text NULL,
    "CompanyId" integer NULL,
    "Posted" timestamp without time zone NULL,
    "Notes" text NULL,
    "Seen" boolean NOT NULL,
    "Archived" boolean NOT NULL,
    "Status" text NOT NULL,
    "DateApplied" timestamp without time zone NULL,
    "Provider" text NULL,
    "ProviderId" text NULL,
    "SourceId" integer NULL,
    CONSTRAINT "PK_Jobs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Jobs_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Jobs_Searches_SourceId" FOREIGN KEY ("SourceId") REFERENCES "Searches" ("Id") ON DELETE SET NULL
);

CREATE TABLE "SearchRuns" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "SearchId" integer NOT NULL,
    "Time" timestamp without time zone NOT NULL,
    "Success" boolean NOT NULL,
    "Message" text NULL,
    "NewJobs" integer NOT NULL,
    "NewCompanies" integer NOT NULL,
    "TimeTaken" integer NOT NULL,
    CONSTRAINT "PK_SearchRuns" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SearchRuns_Searches_SearchId" FOREIGN KEY ("SearchId") REFERENCES "Searches" ("Id") ON DELETE CASCADE
);

CREATE TABLE "JobCategories" (
    "JobId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "PK_JobCategories" PRIMARY KEY ("JobId", "CategoryId"),
    CONSTRAINT "FK_JobCategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_JobCategories_Jobs_JobId" FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CompanyCategories_CategoryId" ON "CompanyCategories" ("CategoryId");

CREATE INDEX "IX_JobCategories_CategoryId" ON "JobCategories" ("CategoryId");

CREATE INDEX "IX_Jobs_CompanyId" ON "Jobs" ("CompanyId");

CREATE INDEX "IX_Jobs_SourceId" ON "Jobs" ("SourceId");

CREATE INDEX "IX_SearchRuns_SearchId" ON "SearchRuns" ("SearchId");

CREATE INDEX "IX_WatchedPages_CompanyId" ON "WatchedPages" ("CompanyId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210606154030_InitialCreate', '5.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "Companies" ADD "Recruiter" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210926181747_CompanyRecruiter', '5.0.9');

COMMIT;
